# Generated by Django 4.1.4 on 2023-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название РЛС')),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(null=True, verbose_name='Описание РЛС')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
        ),
    ]
