# Generated by Django 4.1.4 on 2023-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radar',
            options={'verbose_name': 'РЛС', 'verbose_name_plural': 'РЛС'},
        ),
        migrations.AddField(
            model_name='radar',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='radar',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
