# Generated by Django 4.1.4 on 2023-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0002_alter_radar_options_radar_image_alter_radar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
