# Generated by Django 4.1.4 on 2023-02-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0009_alter_radar_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radar',
            name='data',
        ),
    ]
