# Generated by Django 4.1.4 on 2023-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0010_remove_radar_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='radar',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
